### ISSUE TITLE
使用 Shizuku 调用系统API

### ISSUE THREAD

**Issue by Deep-Fog** [heiha100/Moven#11]
软件中的某些权限并不能使用系统权限管理器进行授权，因此使用 Shizuku 获取更高权限的 API 来实现 AOD （息屏显示）以及常亮这种功能似乎是个不错的选择。

**Comment by heiha100** [comment]
常亮已经修复了，github上还没更新，酷安上有最新的包。权限我是按照Android14 MIUI系统申请的，android低版本和其他厂商的权限和可能略有不同。把能给的权限都给了应该可以自动启动。如果不行，可以提供下机型和系统版本，以及哪些权限找不到。

发自我的小米
在 DeepFog ***@***.***>，2023年12月9日 13:43写道：

软件中的某些权限并不能使用系统权限管理器进行授权，因此使用 Shizuku 获取更高权限的 API 来实现 AOD （息屏显示）以及常亮这种功能似乎是个不错的选择。

**Comment by Deep-Fog** [comment]
感谢回复:)
我设想的功能是当息屏后自启动 Moven ，但我的系统权限管理器里好像没有这些权限的选项。
机型是 LG G8 ThinQ，系统是基于 Android12 的 LGUX ，应该所有基于 Android12 的类原生都是差不多的情况。

**Comment by heiha100** [comment]
等我回家给你演示看看，我用pixel没有问题

发自我的小米
在 DeepFog ***@***.***>，2023年12月9日 15:04写道：

感谢回复:)
我设想的功能是当息屏后自启动 Moven ，但我的系统权限管理器里好像没有这些权限的选项。
机型是 LG G8 ThinQ，系统是基于 Android12 的 LGUX ，应该所有基于 Android12 的类原生都是差不多的情况。

**Comment by Deep-Fog** [comment]
好的

**Comment by heiha100** [comment]
https://github.com/heiha100/Moven/assets/134051067/73000aa0-1213-41f3-8c1d-f83afdce3bc5

我用的Pixel2, android11, 系统只提供了后台运行(即电池优化)和悬浮窗两个权限, 这两个权限授予了并且打开「自动启动开关」, 熄屏后即可自动启动Moven

**Comment by heiha100** [comment]
@DeepFog-ORG 实际上原生或者类原生应该只有这两个权限, 自启动和锁屏显示一般第三方系统才有, 后台弹出界面好像只有MIUI有

**Comment by Deep-Fog** [comment]
Yes 发现我的条件选单勾选了充电选项，也就是说刚才我没有充电所以息屏才没有触发🥲
把充电选项勾掉就成功触发了
